### ISSUE TITLE
Allow for whitelisting certain paths

### ISSUE THREAD

**Issue by jrgleason** [auth0/express-oauth2-bearer#35]
### Describe the problem you'd like to have solved

I have a situation using express router where I want the GET commands of say 3 out of 20 endpoints to not check the access token. Currently there doesn't seem to be this sort of white list feature

### Describe the ideal solution

I could pass a list of "public" paths that will be ignored by the authentication header check.

## Alternatives and current work-arounds

Add the express-oauth2-bearer library once for each router

**Comment by adamjmcgrath** [comment]
Hi @jrgleason - this repo is experimental and will be archived. For protecting express resources with access token, we recommend https://github.com/auth0/node-oauth2-jwt-bearer/tree/main/packages/express-oauth2-jwt-bearer (see https://auth0.com/blog/introducing-oauth2-express-sdk-protecting-api-with-jwt/#What-s-Happening-to--express-jwt----express-jwt-authz---and--jwks-rsa- for more details)

For your specific problem, you could try checking out [express-unless](https://github.com/jfromaniello/express-unless)
