### ISSUE TITLE
Web Socket Support

### ISSUE THREAD

**Issue by yeasir01** [auth0/express-oauth2-bearer#51]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/express-oauth2-bearer#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-oauth2-bearer/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Problem:
WebSocket connections are becoming increasingly important in modern web applications, particularly for real-time communication. Currently, the express-oauth2-bearer library is designed primarily for validating OAuth 2.0 access tokens in Express.js HTTP routes. However, it lacks support for WebSocket connections.

Use Case:
Modern web applications often require both HTTP and WebSocket protocols for various functionalities. Integrating OAuth 2.0 authentication seamlessly with WebSocket connections would simplify the authentication process for applications that use both protocols.

### Describe the ideal solution

Ideal Solution:
The ideal solution is to extend the functionality of the express-oauth2-bearer library to support WebSocket middleware. This extension should provide a similar level of ease and security for OAuth 2.0 authentication in WebSocket connections as it currently does for HTTP routes. It should include middleware for WebSocket handshake validation and token decoding.

### Alternatives and current workarounds

Alternatives and Workarounds:
Currently, users have to manually handle token validation and decoding for WebSocket connections, as the express-oauth2-bearer library is primarily designed for HTTP routes. While this manual approach works, it is less convenient and maintainable than having built-in support within the library. An alternative would be to use separate OAuth 2.0 authentication solutions for WebSocket connections, which can lead to duplicated code and increased complexity.

### Additional context

WebSocket connections and HTTP requests have different characteristics, so implementing WebSocket support within the library might require adjustments or new APIs to handle WebSocket authentication seamlessly.
This feature request aims to enhance the library's versatility and usefulness in modern web application development, where a unified authentication approach across different protocols can simplify development and improve security.
Providing support for WebSocket middleware would align with the evolving needs of web applications that increasingly rely on real-time features and OAuth 2.0 authentication.
Is this feature request related to a problem? Please describe.

Yes, this feature request is related to the need for consistent and secure OAuth 2.0 authentication across both HTTP and WebSocket connections in modern web applications.

**Comment by adamjmcgrath** [comment]
Hi @yeasir01 

per the [README](https://github.com/auth0/express-oauth2-bearer), This SDK reached EOL on June 30, 2023 - so is no longer supported - this project will be archived soon.

It has been replaced by https://github.com/auth0/node-oauth2-jwt-bearer (more info https://auth0.com/blog/introducing-oauth2-express-sdk-protecting-api-with-jwt/)

Adding WebSocket support would be out of scope for an Express SDK, but you're welcome to raise a product request for a new SDK here https://community.auth0.com/t/how-do-i-submit-product-feedback-or-feature-requests/22150
